-- Pusula X dashboard yetkileri 02.10.2026 da kaldirildi (778, PUSULAXDEMO, TEST haric). Bu betik ESKI degerleri geri yazar.
UPDATE [1895_RAI].dbo.Users SET DashboardId = 30 WHERE user_ID = 1; -- Admin
UPDATE [1895_RAI].dbo.Users SET DashboardId = 30 WHERE user_ID = 4; -- KOZZY
UPDATE [1895_RAI].dbo.Users SET DashboardId = 30 WHERE user_ID = 5; -- MERKEZ
UPDATE [3666_TIKIZGOLDX].dbo.Users SET DashboardId = 48 WHERE user_ID = 1; -- Admin
UPDATE [3666_TIKIZGOLDX].dbo.Users SET DashboardId = 50 WHERE user_ID = 3; -- SARRAFIYE
UPDATE [3666_TIKIZGOLDX].dbo.Users SET DashboardId = 49 WHERE user_ID = 4; -- CARSI
UPDATE [3844_ASYABURMA].dbo.Users SET DashboardId = 254 WHERE user_ID = 1; -- Admin
UPDATE [3885_MELISAPRK].dbo.Users SET DashboardId = 191 WHERE user_ID = 1; -- Admin
UPDATE [3885_MELISAPRK].dbo.Users SET DashboardId = 191 WHERE user_ID = 6; -- KOLN
UPDATE [4448_ZEBERCEDX].dbo.Users SET DashboardId = 19 WHERE user_ID = 1; -- Admin
UPDATE [4557_ANTOZAY].dbo.Users SET DashboardId = 11 WHERE user_ID = 1; -- Admin
UPDATE [4557_ANTOZAY].dbo.Users SET DashboardId = 11 WHERE user_ID = 7; -- MUHASEBE
UPDATE [4558_ASAYRA].dbo.Users SET DashboardId = 28 WHERE user_ID = 1; -- Admin
UPDATE [4646_BASCILAR_GULTEPE].dbo.Users SET DashboardId = 24 WHERE user_ID = 1; -- Admin
UPDATE [4646_BASCILAR_GULTEPE].dbo.Users SET DashboardId = 24 WHERE user_ID = 2; -- GULTEPE
UPDATE [4646_BASCILAR_GULTEPE].dbo.Users SET DashboardId = 24 WHERE user_ID = 6; -- CADDE
UPDATE [4646_BASCILAR_GULTEPE].dbo.Users SET DashboardId = 24 WHERE user_ID = 7; -- ÇARŞI
UPDATE [5804_Izer_Demo].dbo.Users SET DashboardId = 49 WHERE user_ID = 2; -- Kullanıcı
UPDATE [6030_ROYA].dbo.Users SET DashboardId = 11 WHERE user_ID = 1; -- Admin
UPDATE [6030_ROYAULAS].dbo.Users SET DashboardId = 11 WHERE user_ID = 1; -- Admin
UPDATE [6472_GOLDBAY].dbo.Users SET DashboardId = 49 WHERE user_ID = 2; -- Kullanıcı
UPDATE [6502_YURDAGUL].dbo.Users SET DashboardId = 44 WHERE user_ID = 50; -- Admin
UPDATE [6521_YZCGOLD].dbo.Users SET DashboardId = 191 WHERE user_ID = 1; -- Admin
UPDATE [6521_YZCGOLD].dbo.Users SET DashboardId = 49 WHERE user_ID = 2; -- Kullanıcı
UPDATE [6524_AHTOZAY].dbo.Users SET DashboardId = 254 WHERE user_ID = 1; -- MERT
UPDATE [6524_AHTOZAY].dbo.Users SET DashboardId = 254 WHERE user_ID = 2; -- UGUR GUNEYARSLAN
UPDATE [6674_GOLDART].dbo.Users SET DashboardId = 310 WHERE user_ID = 1; -- Admin
UPDATE [6674_GOLDART].dbo.Users SET DashboardId = 49 WHERE user_ID = 2; -- Kullanıcı
UPDATE [6675_GOLDART2].dbo.Users SET DashboardId = 310 WHERE user_ID = 1; -- Admin
UPDATE [6675_GOLDART2].dbo.Users SET DashboardId = 49 WHERE user_ID = 2; -- Kullanıcı
UPDATE [6713_ELAY].dbo.Users SET DashboardId = 49 WHERE user_ID = 2; -- Kullanıcı
UPDATE [6735_SHAPE].dbo.Users SET DashboardId = 49 WHERE user_ID = 2; -- Kullanıcı
UPDATE [6742_CAN].dbo.Users SET DashboardId = 254 WHERE user_ID = 1; -- Admin
UPDATE [6742_CAN].dbo.Users SET DashboardId = 49 WHERE user_ID = 2; -- Kullanıcı
UPDATE [6754_HAS].dbo.Users SET DashboardId = 49 WHERE user_ID = 2; -- Kullanıcı
UPDATE [6772_YZCGOLDDENIZLI].dbo.Users SET DashboardId = 11 WHERE user_ID = 1; -- Admin
UPDATE [6772_YZCGOLDDENIZLI].dbo.Users SET DashboardId = 49 WHERE user_ID = 2; -- Kullanıcı
UPDATE [6787_BEREKET].dbo.Users SET DashboardId = 254 WHERE user_ID = 1; -- Admin
UPDATE [6787_BEREKET].dbo.Users SET DashboardId = 49 WHERE user_ID = 2; -- Kullanıcı
UPDATE [6796_ALTINSEV_TPT].dbo.Users SET DashboardId = 86 WHERE user_ID = 1; -- Admin
UPDATE [6796_ALTINSEV_X].dbo.Users SET DashboardId = 11 WHERE user_ID = 1; -- Admin
UPDATE [6796_ALTINSEV_X].dbo.Users SET DashboardId = 49 WHERE user_ID = 2; -- Kullanıcı
UPDATE [6802_HERA].dbo.Users SET DashboardId = 49 WHERE user_ID = 2; -- Kullanıcı
UPDATE [6809_RESUL].dbo.Users SET DashboardId = 11 WHERE user_ID = 1; -- Admin
UPDATE [6809_RESUL].dbo.Users SET DashboardId = 49 WHERE user_ID = 2; -- Kullanıcı
UPDATE [6810_YAMALIOGLU].dbo.Users SET DashboardId = 24 WHERE user_ID = 1; -- Admin
UPDATE [6842_GOLD_POINT].dbo.Users SET DashboardId = 49 WHERE user_ID = 2; -- Kullanıcı
UPDATE [6842_GOLDPOINT_26].dbo.Users SET DashboardId = 49 WHERE user_ID = 2; -- Kullanıcı
UPDATE [6865_ANKA].dbo.Users SET DashboardId = 49 WHERE user_ID = 2; -- Kullanıcı
UPDATE [6914_KUMLUCARESUL].dbo.Users SET DashboardId = 76 WHERE user_ID = 1; -- Admin
UPDATE [6914_KUMLUCARESUL].dbo.Users SET DashboardId = 49 WHERE user_ID = 2; -- Kullanıcı
UPDATE [6916_ELITGOLD].dbo.Users SET DashboardId = 49 WHERE user_ID = 2; -- Kullanıcı
UPDATE [6925_ZZ_ATELIER].dbo.Users SET DashboardId = 49 WHERE user_ID = 2; -- Kullanıcı
UPDATE [6934_IHSAN_ATES].dbo.Users SET DashboardId = 49 WHERE user_ID = 2; -- Kullanıcı
UPDATE [6979_FURKANBLZ].dbo.Users SET DashboardId = 49 WHERE user_ID = 2; -- Kullanıcı
UPDATE [7002_ASUDEGOLD].dbo.Users SET DashboardId = 49 WHERE user_ID = 2; -- Kullanıcı
UPDATE [7029_FINERECYCLING].dbo.Users SET DashboardId = 49 WHERE user_ID = 2; -- Kullanıcı
UPDATE [7063_MIRIELLA26].dbo.Users SET DashboardId = 49 WHERE user_ID = 2; -- Kullanıcı
