-- ============================================================================
-- Faz 4: Server-monitoring çekirdeği — mssql → Supabase (hub schema)
-- servers, server_roles, ad_users, ad_ous, iis_sites, iis_app_pools,
-- sql_databases, failed_logon_attempts
-- ============================================================================
-- Poller (Coolify'da, agent'larla aynı 10.15.2.x ağı) bu tabloları YAZAR (service-role).
-- Servers.password/sql_password AES ciphertext (text korunur). id'ler text (agent id).
-- ============================================================================

create table if not exists hub.servers (
  id            text primary key,
  name          text not null,
  ip            text not null,
  dns           text,
  os            text,
  status        text,
  cpu           double precision not null default 0,
  ram           double precision not null default 0,
  disk          double precision not null default 0,
  uptime        text,
  last_checked  text,
  created_at    timestamptz not null default now(),
  api_key       text,
  agent_port    int default 5000,
  username      text,
  password      text,                                  -- AES ciphertext
  sql_username  text,
  sql_password  text,                                  -- AES ciphertext
  domain        text,
  rdp_port      int
);

create table if not exists hub.server_roles (
  server_id text not null,
  role      text not null,
  primary key (server_id, role)
);

create table if not exists hub.ad_users (
  id           text primary key,
  username     text not null,
  display_name text,
  email        text,
  ou           text,                                   -- = companies.company_id (firkod)
  enabled      boolean not null default true,
  last_login   timestamptz,
  created_at   date,
  phone        text,
  server       text
);
create index if not exists ad_users_ou_idx on hub.ad_users (ou);

create table if not exists hub.ad_ous (
  id         int generated by default as identity primary key,
  name       text not null,
  path       text not null,
  parent_id  int,
  user_count int not null default 0
);

create table if not exists hub.iis_sites (
  id            text primary key,
  name          text not null,
  server        text not null,
  status        text,
  binding       text,
  app_pool      text,
  physical_path text,
  firma         text,
  hizmet        text
);
create index if not exists iis_sites_server_idx on hub.iis_sites (server);

create table if not exists hub.iis_app_pools (
  name          text primary key,
  status        text,
  runtime       text,
  pipeline_mode text
);

create table if not exists hub.sql_databases (
  id                     text primary key,
  name                   text not null,
  server                 text not null,
  size_mb                int not null default 0,
  status                 text,
  last_backup            timestamptz,
  tables                 int not null default 0,
  firma_no               text,
  recovery_model         text,
  owner                  text,
  data_file_path         text,
  log_file_path          text,
  last_diff_backup       timestamptz,
  last_backup_start      timestamptz,
  last_diff_backup_start timestamptz
);
create index if not exists sql_databases_server_idx on hub.sql_databases (server);

create table if not exists hub.failed_logon_attempts (
  id          bigint generated always as identity primary key,
  server_id   text not null,
  server_name text not null,
  timestamp   timestamptz not null,
  username    text,
  client_ip   text,
  created_at  timestamptz not null default now()
);
create index if not exists failed_logon_ts_idx on hub.failed_logon_attempts (timestamp desc);

alter table hub.servers               enable row level security;
alter table hub.server_roles          enable row level security;
alter table hub.ad_users              enable row level security;
alter table hub.ad_ous                enable row level security;
alter table hub.iis_sites             enable row level security;
alter table hub.iis_app_pools         enable row level security;
alter table hub.sql_databases         enable row level security;
alter table hub.failed_logon_attempts enable row level security;

create policy "hub authed full" on hub.servers               for all to authenticated using (true) with check (true);
create policy "hub authed full" on hub.server_roles          for all to authenticated using (true) with check (true);
create policy "hub authed full" on hub.ad_users              for all to authenticated using (true) with check (true);
create policy "hub authed full" on hub.ad_ous                for all to authenticated using (true) with check (true);
create policy "hub authed full" on hub.iis_sites             for all to authenticated using (true) with check (true);
create policy "hub authed full" on hub.iis_app_pools         for all to authenticated using (true) with check (true);
create policy "hub authed full" on hub.sql_databases         for all to authenticated using (true) with check (true);
create policy "hub authed full" on hub.failed_logon_attempts for all to authenticated using (true) with check (true);

grant all on hub.servers, hub.server_roles, hub.ad_users, hub.ad_ous, hub.iis_sites,
             hub.iis_app_pools, hub.sql_databases, hub.failed_logon_attempts
  to authenticated, service_role;
