-- Pars (mobil raporlama) kullanıcıları — sihirbaz / firma detayı Ayar.mdb'ye
-- yazdığında Hub'da iz bırakır; firma "Hizmetler" sekmesi buradan beslenir.
-- Şifre saklanmaz (Ayar.mdb'de düz metin duruyor, ikinci kopya gereksiz).
create table if not exists hub.company_pars_users (
  id            bigint generated by default as identity primary key,
  company_id    text not null,
  service_id    int  not null references hub.wizard_services(id) on delete cascade,
  username      text not null,
  tipi          int  not null default 0,          -- 1 admin, 0 kullanıcı (Ayar.mdb Users.Tipi)
  pars_user_id  int,                              -- Ayar.mdb Users.ID
  data_names    text,                             -- bağlanan DB adları, virgülle
  created_at    timestamptz not null default now()
);
create index if not exists cpu_company_idx on hub.company_pars_users (company_id);
