-- ============================================================================
-- Pusula giriş ekranı data sırası — değişiklik geçmişi
-- ============================================================================
-- Program giriş ekranında dataları sirket.dbo.guvenlik.srkkod'a göre (büyükten
-- küçüğe) sıralıyor. Firma detayından sıra değiştirilince firmanın KENDİ srkkod
-- numaraları satırlar arasında yer değiştiriyor (IDENTITY_INSERT). Her
-- değişikliğin eski/yeni eşlemesi burada tutulur — "Geri al" buradan okur.
-- eslesme: [{ "dataYolu": "2278_HOSGOR26", "eski": 568, "yeni": 568 }, ...]
-- ============================================================================

create table if not exists hub.giris_sirasi_gecmis (
  id          bigint generated by default as identity primary key,
  company_id  text not null,
  kullanici   text,
  eslesme     jsonb not null,
  geri_alindi boolean not null default false,
  created_at  timestamptz not null default now()
);
create index if not exists gsg_company_idx on hub.giris_sirasi_gecmis (company_id, created_at desc);

alter table hub.giris_sirasi_gecmis enable row level security;
drop policy if exists "hub authed full" on hub.giris_sirasi_gecmis;
create policy "hub authed full" on hub.giris_sirasi_gecmis
  for all to authenticated using (true) with check (true);
