-- ============================================================================
-- Faz 4: Wizard (kurulum sihirbazı) + Demo DB + Panel users — hub schema
-- ============================================================================

create table if not exists hub.wizard_services (
  id            int generated by default as identity primary key,
  name          text not null,
  category      text not null,
  display_order int  not null default 0,
  is_active     boolean not null default true,
  type          text not null default 'pusula-program',
  config        text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create table if not exists hub.wizard_port_ranges (
  id          int generated by default as identity primary key,
  name        text not null,
  port_start  int not null,
  port_end    int not null,
  protocol    text not null default 'TCP',
  description text,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table if not exists hub.wizard_port_assignments (
  id            int generated by default as identity primary key,
  port_range_id int not null references hub.wizard_port_ranges(id) on delete cascade,
  service_id    int not null references hub.wizard_services(id) on delete cascade,
  company_id    text not null,
  port          int not null,
  site_name     text,
  assigned_at   timestamptz not null default now()
);
create index if not exists wpa_company_idx on hub.wizard_port_assignments (company_id);

create table if not exists hub.demo_databases (
  id            int generated by default as identity primary key,
  name          text not null,
  data_name     text not null,
  location_type text not null default 'Yerel',
  location_path text,
  description   text,
  display_order int not null default 0,
  is_active     boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create table if not exists hub.demo_database_services (
  demo_database_id int not null references hub.demo_databases(id) on delete cascade,
  service_id       int not null references hub.wizard_services(id) on delete cascade,
  primary key (demo_database_id, service_id)
);

create table if not exists hub.panel_users (
  id            text primary key,
  name          text not null,
  email         text not null,
  role          text not null,
  password_hash text not null,
  last_active   text,
  created_at    timestamptz not null default now()
);

alter table hub.wizard_services         enable row level security;
alter table hub.wizard_port_ranges      enable row level security;
alter table hub.wizard_port_assignments enable row level security;
alter table hub.demo_databases          enable row level security;
alter table hub.demo_database_services  enable row level security;
alter table hub.panel_users             enable row level security;

create policy "hub authed full" on hub.wizard_services         for all to authenticated using (true) with check (true);
create policy "hub authed full" on hub.wizard_port_ranges      for all to authenticated using (true) with check (true);
create policy "hub authed full" on hub.wizard_port_assignments for all to authenticated using (true) with check (true);
create policy "hub authed full" on hub.demo_databases          for all to authenticated using (true) with check (true);
create policy "hub authed full" on hub.demo_database_services  for all to authenticated using (true) with check (true);
create policy "hub authed full" on hub.panel_users             for all to authenticated using (true) with check (true);

grant all on hub.wizard_services, hub.wizard_port_ranges, hub.wizard_port_assignments,
             hub.demo_databases, hub.demo_database_services, hub.panel_users
  to authenticated, service_role;
