-- ============================================================================
-- Sunucu ölçüm geçmişi — Sunucu Raporu sayfası
-- ============================================================================
-- Poller her 10 sn'de agent'tan CPU / RAM / disk / oturum alıyor ama bunlar
-- yalnız bellekte duruyordu; ESXi (vCenter yok) de yalnız son 1 saati tutuyor.
-- Poller 5 dakikalık kovaları özetleyip buraya yazar (lib/server-metrics.ts).
-- Bir satır = bir sunucunun bir 5 dk'sı. ~10 sunucu × 288/gün ≈ 3 bin satır/gün;
-- 180 günden eskiler poller tarafından silinir.
-- ============================================================================

create table if not exists hub.server_metrics (
  id              bigint generated by default as identity primary key,
  server_id       text        not null,
  server_name     text        not null,
  ts              timestamptz not null,          -- kova başlangıcı (5 dk'ya hizalı)
  samples         int         not null,
  cpu_avg         real,
  cpu_max         real,
  ram_used_mb     int,                           -- ortalama; uygulama + çekirdek (önbellek hariç)
  ram_max_mb      int,
  ram_total_mb    int,
  disk_used_gb    real,                          -- sistem sürücüsü (C: ya da ilk disk), kova sonu
  disk_total_gb   real,
  sessions_active int,                           -- kovadaki en yüksek aktif oturum
  sessions_total  int,                           -- kovadaki en yüksek toplam (aktif + kopuk)
  unique (server_id, ts)
);
create index if not exists server_metrics_ts_idx on hub.server_metrics (ts);

alter table hub.server_metrics enable row level security;
drop policy if exists "hub authed full" on hub.server_metrics;
create policy "hub authed full" on hub.server_metrics
  for all to authenticated using (true) with check (true);

-- Rapor için kova birleştirme: p_bucket_minutes (5, 60, 180…) aralıklarla
-- ortalama/en yüksek. 14 günü 5'er dakikalık ham satır olarak taşımamak için.
create or replace function hub.server_metrics_ozet(p_since timestamptz, p_bucket_minutes int)
returns table (
  server_id text, server_name text, ts timestamptz,
  cpu_avg real, cpu_max real, ram_used_mb int, ram_max_mb int, ram_total_mb int,
  disk_used_gb real, disk_total_gb real, sessions_active int, sessions_total int
)
language sql stable security invoker set search_path = hub, public as $$
  select m.server_id,
         max(m.server_name),
         date_bin(make_interval(mins => greatest(p_bucket_minutes, 5)), m.ts, timestamptz '2026-01-01 00:00+03') as kova,
         round(avg(m.cpu_avg)::numeric, 1)::real,
         max(m.cpu_max),
         avg(m.ram_used_mb)::int,
         max(m.ram_max_mb),
         max(m.ram_total_mb),
         max(m.disk_used_gb),
         max(m.disk_total_gb),
         max(m.sessions_active),
         max(m.sessions_total)
  from hub.server_metrics m
  where m.ts >= p_since
  group by m.server_id, kova
  order by kova, m.server_id
$$;

grant select, insert, update, delete on hub.server_metrics to authenticated, service_role;
grant execute on function hub.server_metrics_ozet(timestamptz, int) to authenticated, service_role;
