import type {
  Server,
  ADUser,
  ADOU,
  SQLDatabase,
  IISSite,
  IISAppPool,
  LogEntry,
  FileItem,
  PanelUser,
  DashboardStats,
  RecentEvent,
  Service,
  Company,
  MessageRecipient,
  Message,
} from "@/types";

export const dashboardStats: DashboardStats = {
  totalServers: 12,
  activeServers: 9,
  warningServers: 2,
  offlineServers: 1,
};

export const servers: Server[] = [
  {
    id: "srv-001",
    name: "DC-PRIMARY",
    ip: "192.168.1.10",
    os: "Windows Server 2022",
    status: "online",
    roles: ["AD", "DNS", "DHCP"],
    cpu: 35,
    ram: 62,
    disk: 45,
    uptime: "45 gun",
    lastChecked: "2 dakika once",
  },
  {
    id: "srv-002",
    name: "SQL-PROD",
    ip: "192.168.1.20",
    os: "Windows Server 2022",
    status: "online",
    roles: ["SQL"],
    cpu: 72,
    ram: 85,
    disk: 68,
    uptime: "30 gun",
    lastChecked: "1 dakika once",
  },
  {
    id: "srv-003",
    name: "WEB-IIS-01",
    ip: "192.168.1.30",
    os: "Windows Server 2019",
    status: "online",
    roles: ["IIS"],
    cpu: 28,
    ram: 45,
    disk: 32,
    uptime: "60 gun",
    lastChecked: "3 dakika once",
  },
  {
    id: "srv-004",
    name: "WEB-IIS-02",
    ip: "192.168.1.31",
    os: "Windows Server 2019",
    status: "warning",
    roles: ["IIS"],
    cpu: 89,
    ram: 92,
    disk: 78,
    uptime: "15 gun",
    lastChecked: "1 dakika once",
  },
  {
    id: "srv-005",
    name: "FILE-SRV",
    ip: "192.168.1.40",
    os: "Windows Server 2022",
    status: "online",
    roles: ["File"],
    cpu: 12,
    ram: 38,
    disk: 82,
    uptime: "90 gun",
    lastChecked: "5 dakika once",
  },
  {
    id: "srv-006",
    name: "UBUNTU-APP-01",
    ip: "192.168.1.50",
    os: "Ubuntu 24.04",
    status: "online",
    roles: ["General"],
    cpu: 45,
    ram: 55,
    disk: 40,
    uptime: "120 gun",
    lastChecked: "2 dakika once",
  },
  {
    id: "srv-007",
    name: "UBUNTU-APP-02",
    ip: "192.168.1.51",
    os: "Ubuntu 22.04",
    status: "online",
    roles: ["General"],
    cpu: 22,
    ram: 40,
    disk: 35,
    uptime: "95 gun",
    lastChecked: "4 dakika once",
  },
  {
    id: "srv-008",
    name: "UBUNTU-DB",
    ip: "192.168.1.52",
    os: "Ubuntu 24.04",
    status: "warning",
    roles: ["SQL"],
    cpu: 78,
    ram: 88,
    disk: 91,
    uptime: "20 gun",
    lastChecked: "1 dakika once",
  },
  {
    id: "srv-009",
    name: "DC-SECONDARY",
    ip: "192.168.1.11",
    os: "Windows Server 2022",
    status: "online",
    roles: ["AD", "DNS"],
    cpu: 18,
    ram: 42,
    disk: 30,
    uptime: "45 gun",
    lastChecked: "2 dakika once",
  },
  {
    id: "srv-010",
    name: "SQL-DEV",
    ip: "192.168.1.21",
    os: "Windows Server 2019",
    status: "online",
    roles: ["SQL"],
    cpu: 15,
    ram: 35,
    disk: 55,
    uptime: "10 gun",
    lastChecked: "3 dakika once",
  },
  {
    id: "srv-011",
    name: "BACKUP-SRV",
    ip: "192.168.1.60",
    os: "Ubuntu 22.04",
    status: "online",
    roles: ["File"],
    cpu: 8,
    ram: 25,
    disk: 72,
    uptime: "180 gun",
    lastChecked: "6 dakika once",
  },
  {
    id: "srv-012",
    name: "MONITOR-SRV",
    ip: "192.168.1.70",
    os: "Ubuntu 24.04",
    status: "offline",
    roles: ["General"],
    cpu: 0,
    ram: 0,
    disk: 0,
    uptime: "-",
    lastChecked: "2 saat once",
  },
];

export const recentEvents: RecentEvent[] = [
  { id: "evt-1", timestamp: "14:32", server: "SQL-PROD", type: "warning", message: "RAM kullanimi %85 uzerine cikti" },
  { id: "evt-2", timestamp: "14:28", server: "WEB-IIS-02", type: "error", message: "CPU kullanimi kritik seviyede (%89)" },
  { id: "evt-3", timestamp: "14:15", server: "UBUNTU-DB", type: "warning", message: "Disk kullanimi %91 - temizlik gerekli" },
  { id: "evt-4", timestamp: "13:55", server: "DC-PRIMARY", type: "success", message: "AD replikasyonu basariyla tamamlandi" },
  { id: "evt-5", timestamp: "13:40", server: "FILE-SRV", type: "info", message: "Yedekleme islemi tamamlandi" },
  { id: "evt-6", timestamp: "13:22", server: "MONITOR-SRV", type: "error", message: "Sunucu yanit vermiyor" },
  { id: "evt-7", timestamp: "12:58", server: "WEB-IIS-01", type: "success", message: "SSL sertifikasi yenilendi" },
  { id: "evt-8", timestamp: "12:30", server: "UBUNTU-APP-01", type: "info", message: "Sistem guncellenmesi tamamlandi" },
];

export const adUsers: ADUser[] = [
  { id: "usr-1", username: "ahmet.yilmaz", displayName: "Ahmet Yilmaz", email: "ahmet.yilmaz@sirket.local", ou: "IT", enabled: true, lastLogin: "2024-03-29 09:15", createdAt: "2023-01-15" },
  { id: "usr-2", username: "mehmet.kaya", displayName: "Mehmet Kaya", email: "mehmet.kaya@sirket.local", ou: "IT", enabled: true, lastLogin: "2024-03-29 08:45", createdAt: "2023-02-20" },
  { id: "usr-3", username: "ayse.demir", displayName: "Ayse Demir", email: "ayse.demir@sirket.local", ou: "Muhasebe", enabled: true, lastLogin: "2024-03-28 17:30", createdAt: "2023-03-10" },
  { id: "usr-4", username: "fatma.ozturk", displayName: "Fatma Ozturk", email: "fatma.ozturk@sirket.local", ou: "IK", enabled: true, lastLogin: "2024-03-29 08:00", createdAt: "2023-04-05" },
  { id: "usr-5", username: "ali.celik", displayName: "Ali Celik", email: "ali.celik@sirket.local", ou: "Satis", enabled: false, lastLogin: "2024-02-15 12:00", createdAt: "2023-05-18" },
  { id: "usr-6", username: "zeynep.arslan", displayName: "Zeynep Arslan", email: "zeynep.arslan@sirket.local", ou: "Pazarlama", enabled: true, lastLogin: "2024-03-29 09:30", createdAt: "2023-06-22" },
  { id: "usr-7", username: "hasan.yildiz", displayName: "Hasan Yildiz", email: "hasan.yildiz@sirket.local", ou: "IT", enabled: true, lastLogin: "2024-03-29 07:50", createdAt: "2023-07-01" },
  { id: "usr-8", username: "elif.sahin", displayName: "Elif Sahin", email: "elif.sahin@sirket.local", ou: "Yonetim", enabled: true, lastLogin: "2024-03-28 16:45", createdAt: "2022-11-30" },
];

export const adOUTree: ADOU[] = [
  {
    name: "sirket.local",
    path: "DC=sirket,DC=local",
    userCount: 0,
    children: [
      {
        name: "IT",
        path: "OU=IT,DC=sirket,DC=local",
        userCount: 3,
        children: [
          { name: "Sistem Yonetimi", path: "OU=Sistem Yonetimi,OU=IT,DC=sirket,DC=local", userCount: 2, children: [] },
          { name: "Yazilim", path: "OU=Yazilim,OU=IT,DC=sirket,DC=local", userCount: 1, children: [] },
        ],
      },
      { name: "Muhasebe", path: "OU=Muhasebe,DC=sirket,DC=local", userCount: 1, children: [] },
      { name: "IK", path: "OU=IK,DC=sirket,DC=local", userCount: 1, children: [] },
      { name: "Satis", path: "OU=Satis,DC=sirket,DC=local", userCount: 1, children: [] },
      { name: "Pazarlama", path: "OU=Pazarlama,DC=sirket,DC=local", userCount: 1, children: [] },
      { name: "Yonetim", path: "OU=Yonetim,DC=sirket,DC=local", userCount: 1, children: [] },
    ],
  },
];

export const sqlDatabases: SQLDatabase[] = [
  { id: "db-1", name: "ERP_Production", server: "SQL-PROD", sizeMB: 15360, status: "Online", lastBackup: "2024-03-29 02:00", tables: 245 },
  { id: "db-2", name: "HR_System", server: "SQL-PROD", sizeMB: 2048, status: "Online", lastBackup: "2024-03-29 02:30", tables: 58 },
  { id: "db-3", name: "CRM_Data", server: "SQL-PROD", sizeMB: 8192, status: "Online", lastBackup: "2024-03-29 03:00", tables: 132 },
  { id: "db-4", name: "WebApp_DB", server: "SQL-PROD", sizeMB: 4096, status: "Online", lastBackup: "2024-03-29 03:30", tables: 87 },
  { id: "db-5", name: "ERP_Dev", server: "SQL-DEV", sizeMB: 12288, status: "Online", lastBackup: "2024-03-28 22:00", tables: 245 },
  { id: "db-6", name: "TestDB", server: "SQL-DEV", sizeMB: 512, status: "Online", lastBackup: "2024-03-27 18:00", tables: 15 },
  { id: "db-7", name: "Archive_2023", server: "SQL-PROD", sizeMB: 25600, status: "Online", lastBackup: "2024-03-25 02:00", tables: 180 },
];

export const iisSites: IISSite[] = [
  { id: "iis-1", name: "Kurumsal Web", server: "WEB-IIS-01", status: "Started", binding: "https://www.sirket.com:443", appPool: "KurumsalPool", physicalPath: "C:\\inetpub\\wwwroot\\kurumsal" },
  { id: "iis-2", name: "Intranet Portal", server: "WEB-IIS-01", status: "Started", binding: "http://intranet.sirket.local:80", appPool: "IntranetPool", physicalPath: "C:\\inetpub\\wwwroot\\intranet" },
  { id: "iis-3", name: "API Gateway", server: "WEB-IIS-02", status: "Started", binding: "https://api.sirket.com:443", appPool: "ApiPool", physicalPath: "C:\\inetpub\\wwwroot\\api" },
  { id: "iis-4", name: "CRM Web", server: "WEB-IIS-02", status: "Stopped", binding: "https://crm.sirket.com:443", appPool: "CrmPool", physicalPath: "C:\\inetpub\\wwwroot\\crm" },
  { id: "iis-5", name: "Dokuman Yonetimi", server: "WEB-IIS-01", status: "Started", binding: "http://docs.sirket.local:80", appPool: "DocsPool", physicalPath: "C:\\inetpub\\wwwroot\\docs" },
];

export const iisAppPools: IISAppPool[] = [
  { name: "KurumsalPool", status: "Started", runtime: "v4.0", pipelineMode: "Integrated" },
  { name: "IntranetPool", status: "Started", runtime: "v4.0", pipelineMode: "Integrated" },
  { name: "ApiPool", status: "Started", runtime: "No Managed Code", pipelineMode: "Integrated" },
  { name: "CrmPool", status: "Stopped", runtime: "v4.0", pipelineMode: "Integrated" },
  { name: "DocsPool", status: "Started", runtime: "v4.0", pipelineMode: "Classic" },
];

export const logEntries: LogEntry[] = [
  { id: "log-1", timestamp: "2024-03-29 14:32:15", server: "SQL-PROD", level: "warning", source: "Performance Monitor", message: "RAM kullanimi %85 uzerine cikti" },
  { id: "log-2", timestamp: "2024-03-29 14:28:03", server: "WEB-IIS-02", level: "error", source: "IIS", message: "Application pool 'ApiPool' beklenmedik sekilde durdu" },
  { id: "log-3", timestamp: "2024-03-29 14:15:22", server: "UBUNTU-DB", level: "warning", source: "Disk Monitor", message: "Disk kullanimi %91 - /var/lib/mysql" },
  { id: "log-4", timestamp: "2024-03-29 13:55:00", server: "DC-PRIMARY", level: "info", source: "AD Replication", message: "DC-SECONDARY ile replikasyon tamamlandi" },
  { id: "log-5", timestamp: "2024-03-29 13:40:18", server: "FILE-SRV", level: "info", source: "Backup Agent", message: "Gunluk yedekleme basariyla tamamlandi (245 GB)" },
  { id: "log-6", timestamp: "2024-03-29 13:22:45", server: "MONITOR-SRV", level: "critical", source: "Health Check", message: "Sunucu 30 dakikadir yanit vermiyor" },
  { id: "log-7", timestamp: "2024-03-29 12:58:10", server: "WEB-IIS-01", level: "info", source: "Certificate Manager", message: "SSL sertifikasi basariyla yenilendi (*.sirket.com)" },
  { id: "log-8", timestamp: "2024-03-29 12:30:55", server: "UBUNTU-APP-01", level: "info", source: "APT", message: "Sistem guncellemesi tamamlandi (12 paket)" },
  { id: "log-9", timestamp: "2024-03-29 11:45:30", server: "SQL-PROD", level: "info", source: "SQL Agent", message: "ERP_Production yedekleme islemi tamamlandi" },
  { id: "log-10", timestamp: "2024-03-29 10:15:00", server: "DC-PRIMARY", level: "warning", source: "Group Policy", message: "GPO 'Firewall Rules' 3 bilgisayara uygulanamadi" },
];

export const panelUsers: PanelUser[] = [
  { id: "pu-1", name: "Bulut Admin", email: "bulut@sirket.com", role: "admin", lastActive: "Simdi" },
  { id: "pu-2", name: "Mehmet Kaya", email: "mehmet.kaya@sirket.com", role: "operator", lastActive: "5 dakika once" },
  { id: "pu-3", name: "Ayse Demir", email: "ayse.demir@sirket.com", role: "viewer", lastActive: "1 saat once" },
  { id: "pu-4", name: "Ali Celik", email: "ali.celik@sirket.com", role: "operator", lastActive: "3 saat once" },
];

export const services: Service[] = [
  {
    id: "svc-001",
    name: "Active Directory Yonetimi",
    description: "Kullanici hesaplari, grup yonetimi, OU yapisi, GPO yonetimi ve AD replikasyonu hizmetleri",
    category: "Altyapi",
    status: "active",
    servers: ["DC-PRIMARY", "DC-SECONDARY"],
    port: 389,
    protocol: "LDAP/LDAPS",
    createdAt: "2023-01-10",
    updatedAt: "2024-03-15",
    notes: "Tum kullanici hesaplari ve grup politikalari bu hizmet uzerinden yonetilir",
  },
  {
    id: "svc-002",
    name: "DNS Yonetimi",
    description: "Ic ve dis DNS kayitlarinin yonetimi, zone transferleri ve DNS izleme",
    category: "Altyapi",
    status: "active",
    servers: ["DC-PRIMARY", "DC-SECONDARY"],
    port: 53,
    protocol: "DNS",
    createdAt: "2023-01-10",
    updatedAt: "2024-02-20",
  },
  {
    id: "svc-003",
    name: "SQL Server Veritabani Yonetimi",
    description: "Veritabani olusturma, yedekleme, performans izleme, sorgu optimizasyonu",
    category: "Veritabani",
    status: "active",
    servers: ["SQL-PROD", "SQL-DEV"],
    port: 1433,
    protocol: "TDS",
    createdAt: "2023-02-01",
    updatedAt: "2024-03-28",
    notes: "Production ve development ortamlari ayri sunucularda",
  },
  {
    id: "svc-004",
    name: "IIS Web Hosting",
    description: "Web sitesi barindirma, SSL sertifika yonetimi, uygulama havuzu yonetimi",
    category: "Web",
    status: "active",
    servers: ["WEB-IIS-01", "WEB-IIS-02"],
    port: 443,
    protocol: "HTTPS",
    createdAt: "2023-03-15",
    updatedAt: "2024-03-29",
  },
  {
    id: "svc-005",
    name: "Dosya Paylasim Hizmeti",
    description: "SMB/CIFS dosya paylasimi, erisim yetkileri yonetimi, kota yonetimi",
    category: "Altyapi",
    status: "active",
    servers: ["FILE-SRV"],
    port: 445,
    protocol: "SMB",
    createdAt: "2023-01-20",
    updatedAt: "2024-03-10",
  },
  {
    id: "svc-006",
    name: "Sunucu Yedekleme",
    description: "Gunluk otomatik yedekleme, yedek dogrulama, felaket kurtarma plani",
    category: "Yedekleme",
    status: "active",
    servers: ["BACKUP-SRV", "FILE-SRV"],
    createdAt: "2023-04-01",
    updatedAt: "2024-03-29",
    notes: "Her gece 02:00'de otomatik yedekleme calisiyor",
  },
  {
    id: "svc-007",
    name: "Sistem Izleme ve Alarm",
    description: "CPU, RAM, disk izleme, uptime kontrolu, otomatik alarm bildirimleri",
    category: "Izleme",
    status: "maintenance",
    servers: ["MONITOR-SRV"],
    createdAt: "2023-05-10",
    updatedAt: "2024-03-29",
    notes: "MONITOR-SRV sunucusu su anda kapali - bakim devam ediyor",
  },
  {
    id: "svc-008",
    name: "DHCP Yonetimi",
    description: "IP adres dagitimi, DHCP scope yonetimi, rezervasyonlar",
    category: "Altyapi",
    status: "active",
    servers: ["DC-PRIMARY"],
    port: 67,
    protocol: "DHCP",
    createdAt: "2023-01-10",
    updatedAt: "2024-01-15",
  },
  {
    id: "svc-009",
    name: "SSL Sertifika Yonetimi",
    description: "SSL/TLS sertifika temin etme, yenileme, izleme ve dagitim",
    category: "Guvenlik",
    status: "active",
    servers: ["WEB-IIS-01", "WEB-IIS-02"],
    port: 443,
    protocol: "HTTPS",
    createdAt: "2023-06-01",
    updatedAt: "2024-03-29",
  },
  {
    id: "svc-010",
    name: "Linux Uygulama Sunucusu",
    description: "Docker container yonetimi, uygulama deploy, log yonetimi",
    category: "Web",
    status: "active",
    servers: ["UBUNTU-APP-01", "UBUNTU-APP-02"],
    createdAt: "2023-07-15",
    updatedAt: "2024-03-20",
  },
  {
    id: "svc-011",
    name: "Firewall Yonetimi",
    description: "Ag guvenlik kurallari, port yonetimi, erisim kontrol listeleri",
    category: "Guvenlik",
    status: "active",
    servers: ["DC-PRIMARY", "WEB-IIS-01", "WEB-IIS-02"],
    createdAt: "2023-02-10",
    updatedAt: "2024-03-25",
  },
  {
    id: "svc-012",
    name: "MySQL Veritabani",
    description: "Linux tabanli MySQL veritabani yonetimi ve yedekleme",
    category: "Veritabani",
    status: "active",
    servers: ["UBUNTU-DB"],
    port: 3306,
    protocol: "MySQL",
    createdAt: "2023-08-01",
    updatedAt: "2024-03-28",
    notes: "Disk kullanimi yuksek - kapasite artirimi planlanmali",
  },
];

export const companies: Company[] = [
  {
    id: "comp-1",
    name: "Pusula Teknoloji",
    sector: "Bilisim",
    contactPerson: "Ahmet Yilmaz",
    contactEmail: "ahmet@pusula.com",
    contactPhone: "0212 555 01 01",
    userCount: 12,
    servers: ["DC-PRIMARY", "SQL-PROD", "WEB-IIS-01", "FILE-SRV"],
    services: [
      { name: "Active Directory", status: "active" },
      { name: "SQL Server Veritabani", status: "active" },
      { name: "IIS Web Hosting", status: "active" },
      { name: "Dosya Paylasim", status: "active" },
      { name: "Yedekleme", status: "active" },
    ],
    status: "active",
    contractStart: "2023-01-01",
    contractEnd: "2025-12-31",
    monthlyQuota: { cpu: 40, ram: 32, disk: 500 },
    currentUsage: { cpu: 28, ram: 24, disk: 320 },
    notes: "Premium musteri - 7/24 destek",
  },
  {
    id: "comp-2",
    name: "Yildiz Holding",
    sector: "Finans",
    contactPerson: "Hasan Yildiz",
    contactEmail: "hasan@yildiz.com",
    contactPhone: "0212 555 02 02",
    userCount: 8,
    servers: ["DC-PRIMARY", "SQL-PROD", "WEB-IIS-02"],
    services: [
      { name: "Active Directory", status: "active" },
      { name: "SQL Server Veritabani", status: "active" },
      { name: "IIS Web Hosting", status: "active" },
      { name: "SSL Sertifika", status: "active" },
    ],
    status: "active",
    contractStart: "2023-06-01",
    contractEnd: "2025-05-31",
    monthlyQuota: { cpu: 30, ram: 24, disk: 300 },
    currentUsage: { cpu: 22, ram: 20, disk: 185 },
  },
  {
    id: "comp-3",
    name: "Atlas Lojistik",
    sector: "Lojistik",
    contactPerson: "Elif Sahin",
    contactEmail: "elif@atlas.com",
    contactPhone: "0216 555 03 03",
    userCount: 5,
    servers: ["DC-PRIMARY", "UBUNTU-APP-01"],
    services: [
      { name: "Active Directory", status: "active" },
      { name: "Linux Uygulama Sunucusu", status: "active" },
    ],
    status: "active",
    contractStart: "2024-01-01",
    contractEnd: "2025-12-31",
    monthlyQuota: { cpu: 20, ram: 16, disk: 200 },
    currentUsage: { cpu: 12, ram: 10, disk: 85 },
  },
  {
    id: "comp-4",
    name: "Deniz Sigorta",
    sector: "Sigortacilik",
    contactPerson: "Selin Koc",
    contactEmail: "selin@deniz.com",
    contactPhone: "0212 555 04 04",
    userCount: 6,
    servers: ["DC-PRIMARY", "SQL-PROD", "WEB-IIS-01"],
    services: [
      { name: "Active Directory", status: "active" },
      { name: "SQL Server Veritabani", status: "active" },
      { name: "IIS Web Hosting", status: "active" },
      { name: "Yedekleme", status: "inactive" },
    ],
    status: "active",
    contractStart: "2023-09-01",
    contractEnd: "2025-08-31",
    monthlyQuota: { cpu: 25, ram: 20, disk: 250 },
    currentUsage: { cpu: 18, ram: 16, disk: 190 },
    notes: "Yedekleme hizmeti talep edildi, aktivasyon bekleniyor",
  },
  {
    id: "comp-5",
    name: "Kale Insaat",
    sector: "Insaat",
    contactPerson: "Murat Aksoy",
    contactEmail: "murat@kale.com",
    contactPhone: "0216 555 05 05",
    userCount: 4,
    servers: ["DC-PRIMARY", "FILE-SRV"],
    services: [
      { name: "Active Directory", status: "active" },
      { name: "Dosya Paylasim", status: "active" },
    ],
    status: "trial",
    contractStart: "2024-03-01",
    contractEnd: "2024-06-01",
    monthlyQuota: { cpu: 10, ram: 8, disk: 100 },
    currentUsage: { cpu: 4, ram: 3, disk: 42 },
    notes: "Deneme sureci - 3 aylik",
  },
];

export const messageRecipients: MessageRecipient[] = [
  { id: "rcpt-1", name: "Ahmet Yilmaz", email: "ahmet@pusula.com", company: "Pusula Teknoloji", server: "DC-PRIMARY", online: true },
  { id: "rcpt-2", name: "Mehmet Kaya", email: "mehmet@pusula.com", company: "Pusula Teknoloji", server: "DC-PRIMARY", online: true },
  { id: "rcpt-3", name: "Ayse Demir", email: "ayse@pusula.com", company: "Pusula Teknoloji", server: "SQL-PROD", online: false },
  { id: "rcpt-4", name: "Fatma Ozturk", email: "fatma@pusula.com", company: "Pusula Teknoloji", server: "WEB-IIS-01", online: true },
  { id: "rcpt-5", name: "Hasan Yildiz", email: "hasan@yildiz.com", company: "Yildiz Holding", server: "DC-PRIMARY", online: true },
  { id: "rcpt-6", name: "Zeynep Arslan", email: "zeynep@yildiz.com", company: "Yildiz Holding", server: "SQL-PROD", online: false },
  { id: "rcpt-7", name: "Ali Celik", email: "ali@yildiz.com", company: "Yildiz Holding", server: "WEB-IIS-02", online: true },
  { id: "rcpt-8", name: "Elif Sahin", email: "elif@atlas.com", company: "Atlas Lojistik", server: "UBUNTU-APP-01", online: true },
  { id: "rcpt-9", name: "Burak Demir", email: "burak@atlas.com", company: "Atlas Lojistik", server: "DC-PRIMARY", online: false },
  { id: "rcpt-10", name: "Selin Koc", email: "selin@deniz.com", company: "Deniz Sigorta", server: "DC-PRIMARY", online: true },
  { id: "rcpt-11", name: "Emre Yildirim", email: "emre@deniz.com", company: "Deniz Sigorta", server: "SQL-PROD", online: true },
  { id: "rcpt-12", name: "Canan Ozdemir", email: "canan@kale.com", company: "Kale Insaat", server: "FILE-SRV", online: false },
  { id: "rcpt-13", name: "Murat Aksoy", email: "murat@kale.com", company: "Kale Insaat", server: "DC-PRIMARY", online: true },
];

export const messages: Message[] = [
  {
    id: "msg-1",
    subject: "Planlı Bakım Bildirimi - SQL Server",
    body: "29 Mart 2024 saat 02:00-04:00 arası SQL-PROD sunucusunda planlı bakım yapılacaktır. Bu süre zarfında veritabanı hizmetlerinde kesinti yaşanabilir.",
    priority: "high",
    sender: "Bulut Admin",
    recipients: ["Tum Kullanicilar"],
    recipientType: "all",
    status: "delivered",
    sentAt: "2024-03-28 16:00",
    readCount: 28,
    totalCount: 35,
  },
  {
    id: "msg-2",
    subject: "Yeni VPN Erisim Politikasi",
    body: "1 Nisan 2024 tarihinden itibaren uzaktan erisim icin yeni VPN politikasi devreye girecektir. Lutfen IT departmanindan yeni sertifikanizi talep edin.",
    priority: "urgent",
    sender: "Bulut Admin",
    recipients: ["Pusula Teknoloji", "Yildiz Holding"],
    recipientType: "company",
    company: "Pusula Teknoloji",
    status: "sent",
    sentAt: "2024-03-29 09:30",
    readCount: 8,
    totalCount: 20,
  },
  {
    id: "msg-3",
    subject: "Dosya Sunucu Taşıma İşlemi",
    body: "FILE-SRV sunucusundaki paylaşım klasörleri yeni diske taşınacaktır. İşlem sırasında dosyalara erişimde geçici kesinti olabilir.",
    priority: "normal",
    sender: "Bulut Admin",
    recipients: ["Canan Ozdemir", "Murat Aksoy"],
    recipientType: "selected",
    status: "read",
    sentAt: "2024-03-27 14:15",
    readCount: 2,
    totalCount: 2,
  },
  {
    id: "msg-4",
    subject: "SSL Sertifika Yenileme",
    body: "Web sunucularindaki SSL sertifikalari basariyla yenilenmistir. Herhangi bir sorun yasarsaniz IT'ye bildirin.",
    priority: "normal",
    sender: "Bulut Admin",
    recipients: ["Yildiz Holding"],
    recipientType: "company",
    company: "Yildiz Holding",
    status: "delivered",
    sentAt: "2024-03-29 13:00",
    readCount: 5,
    totalCount: 8,
  },
  {
    id: "msg-5",
    subject: "Acil: WEB-IIS-02 Performans Sorunu",
    body: "WEB-IIS-02 sunucusunda yüksek CPU kullanımı tespit edilmiştir. Sorun üzerinde çalışılmaktadır. Geçici olarak CRM uygulamasına erişimde yavaşlık yaşanabilir.",
    priority: "urgent",
    sender: "Bulut Admin",
    recipients: ["Ali Celik", "Zeynep Arslan"],
    recipientType: "selected",
    status: "delivered",
    sentAt: "2024-03-29 14:30",
    readCount: 1,
    totalCount: 2,
  },
  {
    id: "msg-6",
    subject: "Haftalik Yedekleme Raporu",
    body: "Bu haftaki yedekleme islemleri basariyla tamamlanmistir. Toplam 1.2 TB veri yedeklenmistir.",
    priority: "normal",
    sender: "Bulut Admin",
    recipients: ["Tum Kullanicilar"],
    recipientType: "all",
    status: "read",
    sentAt: "2024-03-25 08:00",
    readCount: 35,
    totalCount: 35,
  },
];

export const sampleFiles: FileItem[] = [
  { name: "Documents", type: "folder", modified: "2024-03-29 10:00" },
  { name: "Backups", type: "folder", modified: "2024-03-29 02:00" },
  { name: "Logs", type: "folder", modified: "2024-03-29 14:30" },
  { name: "Scripts", type: "folder", modified: "2024-03-28 16:00" },
  { name: "config.xml", type: "file", size: 2048, modified: "2024-03-27 09:15" },
  { name: "backup.log", type: "file", size: 156000, modified: "2024-03-29 02:30" },
  { name: "readme.txt", type: "file", size: 512, modified: "2024-03-15 11:00" },
  { name: "deploy.ps1", type: "file", size: 4096, modified: "2024-03-20 14:20" },
];
